// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppConfig holds persistent application settings
 */
export class AppConfig {
    /**
     * Creates a new AppConfig instance.
     * @param {Partial<AppConfig>} [$$source = {}] - The source object to create the AppConfig.
     */
    constructor($$source = {}) {
        if (!("prefix" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prefix"] = "";
        }
        if (!("overlay" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["overlay"] = false;
        }
        if (!("overlay_color" in $$source)) {
            /**
             * Hex or Name
             * @member
             * @type {string}
             */
            this["overlay_color"] = "";
        }
        if (!("overlay_position" in $$source)) {
            /**
             * top-right, top-left, bottom-right, bottom-left
             * @member
             * @type {string}
             */
            this["overlay_position"] = "";
        }
        if (!("file_suffix" in $$source)) {
            /**
             * Suffix for output file, e.g. "_frozen"
             * @member
             * @type {string}
             */
            this["file_suffix"] = "";
        }
        if (!("overwrite_mode" in $$source)) {
            /**
             * If true, overwrite original file
             * @member
             * @type {boolean}
             */
            this["overwrite_mode"] = false;
        }
        if (!("compression_level" in $$source)) {
            /**
             * none, low, medium, high
             * @member
             * @type {string}
             */
            this["compression_level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppConfig(/** @type {Partial<AppConfig>} */($$parsedSource));
    }
}
