// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../internal/config/models.js";

/**
 * CheckDeps checks if system dependencies (GS) are met
 * @returns {$CancellablePromise<void>}
 */
export function CheckDeps() {
    return $Call.ByID(1789610523);
}

/**
 * GetConfig returns current config
 * @returns {$CancellablePromise<config$0.AppConfig>}
 */
export function GetConfig() {
    return $Call.ByID(790323051).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetCurrentNumber returns the next number
 * @returns {$CancellablePromise<number>}
 */
export function GetCurrentNumber() {
    return $Call.ByID(2835224579);
}

/**
 * OnFileDrop handles the file drop event
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function OnFileDrop(paths) {
    return $Call.ByID(601079801, paths);
}

/**
 * ProcessFile freezes the PDF
 * @param {string} inputPath
 * @param {boolean} overlayOverride
 * @param {string} prefixOverride
 * @param {string} positionOverride
 * @param {string} suffixOverride
 * @param {boolean} overwriteMode
 * @param {string} compressionLevel
 * @returns {$CancellablePromise<string>}
 */
export function ProcessFile(inputPath, overlayOverride, prefixOverride, positionOverride, suffixOverride, overwriteMode, compressionLevel) {
    return $Call.ByID(966051994, inputPath, overlayOverride, prefixOverride, positionOverride, suffixOverride, overwriteMode, compressionLevel);
}

/**
 * SelectFile opens a dialog to select a PDF
 * @returns {$CancellablePromise<string>}
 */
export function SelectFile() {
    return $Call.ByID(751046721);
}

/**
 * SetCompressionLevel updates the compression level setting
 * @param {string} level
 * @returns {$CancellablePromise<void>}
 */
export function SetCompressionLevel(level) {
    return $Call.ByID(2863823789, level);
}

/**
 * SetNumberOverride sets the counter config
 * @param {number} val
 * @returns {$CancellablePromise<void>}
 */
export function SetNumberOverride(val) {
    return $Call.ByID(2356315504, val);
}

/**
 * SetOverlayPosition updates the serial number position
 * @param {string} pos
 * @returns {$CancellablePromise<void>}
 */
export function SetOverlayPosition(pos) {
    return $Call.ByID(3859877424, pos);
}

/**
 * SetPrefix updates the serial number prefix
 * @param {string} prefix
 * @returns {$CancellablePromise<void>}
 */
export function SetPrefix(prefix) {
    return $Call.ByID(124361737, prefix);
}

// Private type creation functions
const $$createType0 = config$0.AppConfig.createFrom;
